package cli

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	fscollector "github.com/truelogics/ai-memory/internal/collector/filesystem"
	"github.com/truelogics/ai-memory/internal/domain"
	"github.com/truelogics/ai-memory/internal/normalizer"
	mdparser "github.com/truelogics/ai-memory/internal/parser/markdown"
	"github.com/truelogics/ai-memory/internal/taxonomy"
)

// TaxonomyAuto implements `eng taxonomy auto`: propose a taxonomy from
// what the repository already contains, show what it would do, and write
// it only if the developer says so.
//
// The proposal is generated by internal/taxonomy, not here. This function
// reads the repository, renders, asks, and writes — orchestration, in a
// command whose whole point is that the decision stays with the person
// who owns the repository.
//
// It reads the filesystem rather than the index, because the flow it
// serves is `eng init` then `eng taxonomy auto`, and `eng init` does not
// index. Running the real Collector -> Parser -> Normalizer means the
// evidence is exactly what indexing would see.
func TaxonomyAuto(ctx context.Context, dir string, in io.Reader, out io.Writer, update, assumeYes bool) error {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("taxonomy auto: %w", err)
	}
	target := filepath.Join(absDir, domain.TaxonomyFile)

	existing, hasExisting, err := readTaxonomy(target)
	if err != nil {
		return err
	}
	if hasExisting && !update {
		fmt.Fprintf(out, "Existing taxonomy found: %s\n\n", target)
		fmt.Fprintln(out, "Use `eng taxonomy auto --update` to generate a proposed update.")
		fmt.Fprintln(out, "It will show the change and still ask before writing anything.")
		return nil
	}

	docs, unreadable, err := readRepository(ctx, absDir)
	if err != nil {
		return err
	}
	if len(docs) == 0 {
		fmt.Fprintf(out, "No markdown documents found under %s — nothing to propose from.\n", absDir)
		return nil
	}

	proposal := taxonomy.Propose(docs, existing)
	if unreadable > 0 {
		fmt.Fprintf(out, "%d document(s) could not be read and are not part of this proposal.\n\n", unreadable)
	}
	if !renderProposal(out, proposal, existing, hasExisting, absDir) {
		return nil
	}

	if !assumeYes {
		ok, err := confirm(in, out, "Apply this taxonomy?")
		if err != nil {
			return fmt.Errorf("taxonomy auto: %w", err)
		}
		if !ok {
			fmt.Fprintf(out, "\nNot applied. %s is unchanged.\n", domain.TaxonomyFile)
			return nil
		}
	}

	if err := writeTaxonomy(target, proposal.YAML()); err != nil {
		return err
	}
	fmt.Fprintf(out, "\nTaxonomy saved to %s\n\n", target)

	if err := verifyWritten(target, docs, out); err != nil {
		return err
	}
	fmt.Fprintln(out, "\nRun `eng index` to apply it.")
	return nil
}

// verifyWritten re-reads the file from disk and applies it to the same
// documents, so the report is about what is now on disk rather than what
// was in memory a moment ago.
//
// It does not go through the index. `eng taxonomy auto` is meant to run
// straight after `eng init`, which creates a workspace and does not index
// anything — so a validation that needed an index would print "not
// checked against real documents" at exactly the moment the developer is
// deciding whether to trust it.
func verifyWritten(target string, docs []domain.CanonicalDocument, out io.Writer) error {
	content, err := os.ReadFile(target)
	if err != nil {
		return fmt.Errorf("taxonomy auto: re-read %s: %w", target, err)
	}
	tax, err := domain.ParseTaxonomy(content)
	if err != nil {
		return fmt.Errorf("taxonomy auto: the file just written does not parse: %w", err)
	}

	// Parsing is all three checks at once: ParseTaxonomy rejects invalid
	// YAML, a type outside the canonical set, and an empty pattern.
	fmt.Fprintf(out, "  valid YAML, %d mapping(s), all canonical types\n", len(tax.Mappings()))

	var classified, unknown, overridden int
	for _, d := range docs {
		declared, claims := tax.TypeFor(d.Path)
		switch {
		case d.Type == domain.DocTypeUnknown && claims:
			classified++
		case d.Type == domain.DocTypeUnknown:
			unknown++
		case claims && declared != d.Type:
			overridden++
		}
	}
	fmt.Fprintf(out, "  %d document(s) classified by this file\n", classified)
	fmt.Fprintf(out, "  %d document(s) still unknown\n", unknown)
	fmt.Fprintf(out, "  %d document(s) where front matter overrides a pattern\n", overridden)
	return nil
}

// renderProposal shows the proposal and its measured effect, and reports
// whether there is anything to confirm.
func renderProposal(out io.Writer, p taxonomy.Proposal, existing domain.Taxonomy, hasExisting bool, dir string) bool {
	fmt.Fprintf(out, "Read %d document(s) under %s.\n\n", p.Documents, dir)

	if p.Empty() {
		switch {
		case p.UnknownBefore == 0:
			fmt.Fprintln(out, "Every document here is already classified, by its own front matter or by")
			fmt.Fprintln(out, "its path. There is nothing a taxonomy would add.")
		default:
			fmt.Fprintf(out, "%d document(s) are unclassified, and nothing here identifies what holds them\n", p.UnknownBefore)
			fmt.Fprintln(out, "confidently enough to propose a mapping.")
		}
		printSkipped(out, p)
		printRootNote(out, p)
		if p.UnknownBefore > 0 {
			fmt.Fprintf(out, "\nWrite %s yourself — `eng taxonomy` lists the canonical types.\n", domain.TaxonomyFile)
		}
		return false
	}

	fmt.Fprintln(out, "Proposed taxonomy:")
	fmt.Fprintln(out)
	width := 0
	for _, m := range p.Mappings {
		if len(m.Pattern) > width {
			width = len(m.Pattern)
		}
	}
	for _, m := range p.Mappings {
		fmt.Fprintf(out, "  %-*s → %-14s %s\n", width, m.Pattern, m.Name, m.Evidence)
	}

	if hasExisting {
		printDifference(out, existing, p)
	}

	fmt.Fprintln(out, "\nMeasured impact — counted by applying this file, not estimated:")
	fmt.Fprintln(out)
	for _, m := range p.Mappings {
		fmt.Fprintf(out, "  %-14s +%d\n", m.Name+":", m.Classifies)
	}
	fmt.Fprintf(out, "  %-14s %d → %d\n", "Unknown:", p.UnknownBefore, p.UnknownAfter)

	if len(p.Overridden) > 0 {
		fmt.Fprintf(out, "\n%d document(s) match a pattern but declare their own type in front matter.\n", len(p.Overridden))
		fmt.Fprintln(out, "Front matter wins (RFC-0007), so these are unaffected:")
		printSome(out, p.Overridden, 5)
	}

	printSkipped(out, p)
	printRootNote(out, p)
	fmt.Fprintln(out, "\nThis is a proposal. Read it — it is a claim about what your directories")
	fmt.Fprintln(out, "mean, and a wrong mapping returns confidently mislabelled documents.")
	fmt.Fprintln(out)
	return true
}

// printDifference names what an --update run would change, since a
// developer approving a rewrite of a file they wrote needs to see the
// delta rather than re-read the whole thing.
func printDifference(out io.Writer, existing domain.Taxonomy, p taxonomy.Proposal) {
	var added []string
	for _, m := range p.Mappings {
		if _, had := declaredFor(existing, m.Pattern); !had {
			added = append(added, m.Pattern+" → "+m.Name)
		}
	}

	fmt.Fprintln(out, "\nAgainst your existing file — an update adds, it does not replace:")
	printGroup(out, "added", added)
	fmt.Fprintf(out, "  kept: %d line(s) you already wrote, unchanged\n", len(existing.Mappings()))
	fmt.Fprintln(out, "\n  Your lines are never rewritten or removed. This proposal has evidence")
	fmt.Fprintln(out, "  for what it can see and none for what it cannot, and treating \"no")
	fmt.Fprintln(out, "  evidence\" as \"delete this\" would discard a decision you made on purpose.")
}

func printGroup(out io.Writer, label string, lines []string) {
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(out, "  %s:\n", label)
	for _, l := range lines {
		fmt.Fprintf(out, "    %s\n", l)
	}
}

func declaredFor(t domain.Taxonomy, pattern string) (string, bool) {
	for _, m := range t.Mappings() {
		if m.Pattern == pattern {
			return m.Declared, true
		}
	}
	return "", false
}

func printSkipped(out io.Writer, p taxonomy.Proposal) {
	if len(p.Skipped) == 0 {
		return
	}
	fmt.Fprintf(out, "\nConsidered and not proposed (%d):\n", len(p.Skipped))
	for i, s := range p.Skipped {
		if i == 5 {
			fmt.Fprintf(out, "  ... and %d more\n", len(p.Skipped)-5)
			break
		}
		fmt.Fprintf(out, "  %-24s %d unclassified — %s\n", s.Pattern, s.Unknown, s.Reason)
	}
}

// printRootNote accounts for the unclassified documents no proposal can
// reach, so the numbers on screen add up.
func printRootNote(out io.Writer, p taxonomy.Proposal) {
	if p.RootUnknown == 0 {
		return
	}
	fmt.Fprintf(out, "\n%d unclassified document(s) sit in the repository root, which no directory\n", p.RootUnknown)
	fmt.Fprintln(out, "pattern can claim. Give them `doc:` front matter, or move them into a")
	fmt.Fprintln(out, "directory that says what they are.")
}

func printSome(out io.Writer, items []string, limit int) {
	for i, item := range items {
		if i == limit {
			fmt.Fprintf(out, "  ... and %d more\n", len(items)-limit)
			return
		}
		fmt.Fprintf(out, "  %s\n", item)
	}
}

// confirm asks and defaults to no. Anything other than an explicit yes
// leaves the repository alone, including EOF: a command that treated a
// closed stdin as approval would write the file in exactly the automated
// contexts where nobody is watching.
func confirm(in io.Reader, out io.Writer, question string) (bool, error) {
	fmt.Fprintf(out, "%s [y/N] ", question)
	line, err := bufio.NewReader(in).ReadString('\n')
	if err != nil && line == "" {
		return false, nil
	}
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes":
		return true, nil
	}
	return false, nil
}

// readTaxonomy loads an existing file. A malformed one is an error, not
// an absence: overwriting a file whose contents could not be read would
// destroy a statement the repository was trying to make.
func readTaxonomy(path string) (domain.Taxonomy, bool, error) {
	content, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return domain.Taxonomy{}, false, nil
	}
	if err != nil {
		return domain.Taxonomy{}, false, fmt.Errorf("taxonomy auto: read %s: %w", path, err)
	}
	tax, err := domain.ParseTaxonomy(content)
	if err != nil {
		return domain.Taxonomy{}, true, fmt.Errorf("taxonomy auto: %s exists but does not parse: %w\n"+
			"Fix or remove it first — this command will not overwrite a file it cannot read", path, err)
	}
	return tax, true, nil
}

// writeTaxonomy writes via a temporary file in the same directory, so an
// interrupted write cannot leave a repository holding half a taxonomy.
func writeTaxonomy(path, content string) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".engineering-*.yaml")
	if err != nil {
		return fmt.Errorf("taxonomy auto: %w", err)
	}
	defer os.Remove(tmp.Name())

	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return fmt.Errorf("taxonomy auto: write %s: %w", tmp.Name(), err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("taxonomy auto: %w", err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("taxonomy auto: %w", err)
	}
	return nil
}

// readRepository runs the real pipeline up to the point a taxonomy would
// be applied, so the proposal reasons about the same documents, with the
// same types, that indexing will.
func readRepository(ctx context.Context, absDir string) ([]domain.CanonicalDocument, int, error) {
	repo, err := domain.NewRepository(defaultWorkspaceID, filepath.Base(absDir), absDir)
	if err != nil {
		return nil, 0, fmt.Errorf("taxonomy auto: %w", err)
	}

	raws, err := fscollector.New().Collect(ctx, repo)
	if err != nil {
		return nil, 0, fmt.Errorf("taxonomy auto: collect %s: %w", absDir, err)
	}

	parser := mdparser.New()
	norm := normalizer.New()
	docs := make([]domain.CanonicalDocument, 0, len(raws))
	unreadable := 0
	for _, raw := range raws {
		if !parser.CanParse(raw) {
			continue
		}
		// One unreadable document must not stop a proposal about the other
		// hundred — but it is counted and reported. This command goes out
		// of its way to account for every document it saw, and a silent
		// drop is the one hole in that: "Read 94 document(s)" with six
		// missing reads as ninety-four.
		doc, err := parser.Parse(ctx, raw)
		if err != nil {
			unreadable++
			continue
		}
		if doc, err = norm.Normalize(ctx, doc); err != nil {
			unreadable++
			continue
		}
		docs = append(docs, doc)
	}
	return docs, unreadable, nil
}
